services:
  - type: web
    name: ocean-spy-buoy
    env: docker
    dockerfilePath: ./Dockerfile
    region: oregon
    plan: free
    envVars:
      - key: MODE
        value: SIMULATION
      - key: DATABASE_URL
        value: sqlite:///./ocean_spy_buoy.db
